name: mr1_build

on:
  # Trigger when commits are pushed to the main branch
  push:
    branches:
      - main

  # Trigger when a pull request is opened against the main branch
  pull_request:
    branches: ["main"]
    types: [opened]

jobs:
  build:
    # Create a container of ubuntu-22.04
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install ROS2 dependencies
      - name: Install ROS2 dependencies
        run: |
          sudo apt update
          sudo apt install -y curl gnupg2 lsb-release
          curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2.list'
          sudo apt update
          sudo apt install -y ros-humble-desktop

      # Install colcon
      - name: Install colcon
        run: sudo apt install -y python3-colcon-common-extensions

      # Build ROS2 packages using colcon
      - name: Build packages
        run: colcon build

      - name: Install Packages
        run: cp -r onboard_pkgs/* ~/robot_ws/src/

      # # Deploy packages to Raspberry Pi
      # - name: Deploy packages to Raspberry Pi
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: 192.168.0.72 # Raspberry Pi IP address or hostname
      #     # host: ${{ secrets.PI_HOST }} # Raspberry Pi IP address or hostname
      #     username: ${{ secrets.PI_USERNAME }} # Raspberry Pi username
      #     password: ${{ secrets.PI_PASSWORD }} # Raspberry Pi password
      #     script: |
      #       scp -r onboard_pkgs/* ${{ secrets.PI_USERNAME }}@${{ secrets.PI_HOST }}:~/robot_ws/src/
