name: mr1_build

on:
  # Trigger when commits are pushed to the main branch
  push:
    branches:
      - main

  # Trigger when a pull request is opened against the main branch
  pull_request:
    branches: ["main"]
    types: [opened]

jobs:
  build:
    # Create a container of ubuntu-22.04
    runs-on: ubuntu-22.04

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install ROS2 dependencies
      - name: Install ROS2 dependencies
        run: |
          sudo apt update
          sudo apt install -y curl gnupg2 lsb-release
          curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2.list'
          sudo apt update
          sudo apt install -y ros-foxy-desktop

      # Install colcon
      - name: Install colcon
        run: sudo apt install -y python3-colcon-common-extensions

      # Build ROS2 packages using colcon
      - name: Build packages
        run: colcon build --packages-up-to dev_test_pkg test_pkg

    # steps:
    #   - name: Install ROS2 Humble packages
    #     run: |
    #       sudo apt update
    #       sudo apt install -y software-properties-common
    #       sudo add-apt-repository universe
    #       sudo apt update && sudo apt install -y curl
    #       sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
    #       echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
    #       sudo apt update
    #       sudo apt install -y ros-humble-ros-base python3-colcon-common-extensions
    #       sudo apt install -y lcov

    #   # We want to use GitHub's checkout version 3 action for checking out the branch
    #   - uses: actions/checkout@v3
    #     with:
    #       path: ~/ros_ws/src/mr1

    #   - name: Setup and Build the workspace
    #     run: |
    #       source /opt/ros/humble/setup.bash
    #       mkdir -p ~/ros_ws/src/mr1
    #       if [ -d "mr1/dev_pkgs" ] && [ -d "mr1/onboard_pkgs" ]; then
    #         cp -r mr1/dev_pkgs/* mr1/onboard_pkgs/* ~/ros_ws/src/mr1
    #       else
    #         echo "ERROR: 'dev_pkgs' or 'onboard_pkgs' directory not found in 'mr1' or empty."
    #         exit 1
    #       fi
    #       cd ~/ros_ws
    #       colcon build --cmake-args -DCOVERAGE=1
    #       source install/setup.bash

    #   - name: Visualize mr1 Directory
    #     run: |
    #       echo "Contents of mr1 directory:"
    #       ls -l ~/ros_ws/src/mr1
    #       echo "Directory structure of mr1:"
    #       tree ~/ros_ws/src/mr1

    #   - name: Configure CMake flags and build executables
    #     run: |
    #       source /opt/ros/humble/setup.bash
    #       sudo apt install python3-rosdep
    #       sudo rosdep init
    #       rosdep update --include-eol-distros
    #       cd ~/ros_ws
    #       rosdep install --from-paths src -y --ignore-src
    #       colcon build --cmake-args -DCOVERAGE=1
    #       cat log/latest_build/*/stdout_stderr.log
    #       find build/*/ | grep -E 'gcno' # catch error -- exepct to see .gcno files
